name: Test
on: push
jobs:
  macos:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        platform: ["macos-15", "ubuntu-22.04"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          pip install .
      - name: Test
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: |
          pytest -s
